version: "3.9"
services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  postgres-data:
  mysql-data: